### ISSUE TITLE
Etherpad with mssql server

### ISSUE THREAD

**Issue by jinbullsushil** [ether/ueberDB#100]
I want to connect etherpad with mssql server.

**Comment by exspecto** [comment]
> 
> 
> I want to connect etherpad with mssql server.

I needed this as well and have a pull request in for it.  If you'd like you can grab the code and use it directly (also need to npm install mssql).

[https://github.com/Pita/ueberDB/pull/120](url)

**Comment by JohnMcLear** [comment]
Done :)
