### ISSUE TITLE
MongoDB authSource

### ISSUE THREAD

**Issue by ToniIltanen** [ether/ueberDB#103]
To which setting should the authsource for the authentication database be put?

i already tried to set the settings.dbName=somedb?authSource=authDB, without any luck.
the error i receive is: 

```
TypeError: this.db.open is not a function
    at new MongoKeyValue (/usr/src/pad/src/node_modules/ueberdb2/mongodb_db.js:82:13)
```

Connection to the mongo itself works from the server when manually tested.

**Comment by Kaor** [comment]
same problem here

**Comment by ToniIltanen** [comment]
I solved this using a different fork of UeberDB and custom configurations, ill put the link tomorrow.

**Comment by ToniIltanen** [comment]
in the src/package.json:
"ueberdb2": "git+https://github.com/leandromoreira/ueberDB.git"

in the dockerfile:
RUN npm install mongodb@2.0.25

in the settings.json:
  "dbSettings" : {
    "url": "mongodb://username:password@mongoserver:port/databasename?authSource=admin"
  }

**Comment by JohnMcLear** [comment]
Rip Mongo
