### ISSUE TITLE
Etherpad can't use mongodb

### ISSUE THREAD

**Issue by ljoets** [ether/ueberDB#109]
Hi,
I installed a fresh Etherpad-lite on Debian Stretch.
Etherpad-lite is working fine with dirtydb.
I installed deb mongodb package.
I installed node mongodb package:
```
root@Etherpad:/home/etherpad/etherpad-lite# su -c 'npm install mongodb' etherpad
npm WARN saveError ENOENT: no such file or directory, open '/home/etherpad/etherpad-lite/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/etherpad/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.
```
I defined mongodb database in settings.json Etherpad-lite file, but when I run Etherpad, I have an error in ueberdb2 module:
```
root@Etherpad:/home/etherpad/etherpad-lite# su -c './bin/run.sh' etherpad
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
up to date in 5.609s
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/mongodb_db.js:82
    this.db.open(function (err, colle) {
            ^

TypeError: this.db.open is not a function
    at new MongoKeyValue (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/mongodb_db.js:82:13)
    at exports.database.init (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/mongodb_db.js:34:18)
    at exports.database.init (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/home/etherpad/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/home/etherpad/etherpad-lite/src/node/db/DB.js:41:6)
    at /home/etherpad/etherpad-lite/src/node/server.js:62:8
    at fn (/home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:641:34)
    at Immediate.<anonymous> (/home/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:557:34)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
```

**Comment by HamzaKhait** [comment]
Same problem here. 
Any solution please ?

**Comment by users2010** [comment]
Me too, same problem. But, after install mongodb (npm install mongodb) I installed other dependencies running:  etherpad-lite/bin/installDeps.sh . This step resolved my dependencies, however,  did hapens another error : (Even I setting my mongodb in settings.json) 

"[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]] on mongo connect "


See right below, versions that I used:

node==v6.14.3
etherpad-lit==1.7.0
OS==3.10.0-229.el7.x86_64

**Comment by HamzaKhait** [comment]
My problem was solved by installing mongodb@2.2.28

**Comment by y377** [comment]
> 我也是，同样的问题。 ，在安装 mongodb (npm install mongodb) ，我安装了其他的依赖项：etherpad-lite/bin/installDeps.sh。一个错误：（即使我在 settings.json 中设置了我的 mongodb）
> 
> “[MongoNetworkError: 第一次连接时无法连接到服务器 [localhost:27017] [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]] on mongo connect”
> 
> 见右下方，我使用的版本：
> 
> 节点==v6.14.3 etherpad-lit==1.7.0 操作系统==3.10.0-229.el7.x86_64

**请问你如何在`settings.json`设置的MongoDB?任何回复都很感谢**

**Comment by y377** [comment]
> Me too, same problem. But, after install mongodb (npm install mongodb) I installed other dependencies running: etherpad-lite/bin/installDeps.sh . This step resolved my dependencies, however, did hapens another error : (Even I setting my mongodb in settings.json)
> 
> "[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]] on mongo connect "
> 
> See right below, versions that I used:
> 
> node==v6.14.3 etherpad-lit==1.7.0 OS==3.10.0-229.el7.x86_64

**How do you get to 'Settings' JSON ` set mongodb? Thank you for any reply**
