### ISSUE TITLE
DB Engine for MySQL should be configurable

### ISSUE THREAD

**Issue by ArcticSnowman** [ether/ueberDB#115]
MyISAM is BAD for a clustered database like Galera.  There needs to be the ability to configure the table engine.

**Comment by pcass-epcc** [comment]
Just a quick note to say thanks for what would have probably been hours of debugging if I hadn't seen this

**Comment by JohnMcLear** [comment]
If you can resolve the conflicts here I can look to merge this in.

**Comment by JohnMcLear** [comment]
https://github.com/ether/ueberDB/commit/90bc1a289bdedea62b0ebefdff757a10eccc2400
