### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by muxator** [ether/ueberDB#121]
This library has a lot of stale dependencies.

Some of them have security vulnerabilities.
With bb9a18634e7f I've committed the current `package-lock.json`, so we freeze the current situation and start from there.

The currently outdated packages are:
```
$ npm outdated
Package           Current  Wanted  Latest  Location
async              0.1.15  0.1.15   3.2.0  ueberdb2
cassandra-driver    2.0.1   2.0.1   4.5.0  ueberdb2
dirty               0.9.9   0.9.9   1.1.0  ueberdb2
elasticsearch      15.1.1  15.1.1  16.7.1  ueberdb2
log4js             0.6.22  0.6.22   6.1.2  ueberdb2
mocha               3.2.0   3.2.0   7.1.1  ueberdb2
mongodb            2.0.25  2.0.25   3.5.5  ueberdb2
nano                6.4.4   6.4.4   8.2.2  ueberdb2
pg                  6.1.6   6.1.6  7.18.2  ueberdb2
```

**p.s.**: Github should soon start sending automated security notifications.

**Comment by JohnMcLear** [comment]
Tested each, updated and published new version.
