### ISSUE TITLE
How are tests run? Can we integrate it inside "npm tests"?

### ISSUE THREAD

**Issue by muxator** [ether/ueberDB#122]
In Etherpad, a while ago I integrated the command for running backend tests in package.json, so that they can be run via `npm tests`.

What is the command for running tests on ueberDB? I could do the same here.

**Comment by JohnMcLear** [comment]
No idea, I tried to do that earlier today and just ended up doing it the old fashioned way of running the Etherpad backend tests against each backend.

**Comment by muxator** [comment]
Ok thanks.

**Comment by JohnMcLear** [comment]
``npm test`` now works.
