### ISSUE TITLE
Broken Syntax in MySQL query

### ISSUE THREAD

**Issue by thegcat** [ether/ueberDB#124]
The changes in 7762f0096458bcb1ada3ad634d1a43f99a1354f0 introduced a syntax error in https://github.com/ether/ueberDB/commit/7762f0096458bcb1ada3ad634d1a43f99a1354f0#diff-4a5e89a56b4c9f1b01d3c9330b7f01acR149, at least on MariaDB. 

This needs an `AND` more.

**Comment by JohnMcLear** [comment]
This is what happens when you submit a fix for a fire while being shouted at by a 6 month old and with broken test coverage.

We
need
fucking
test
coverage.

Fixed in 0.4.7

**Comment by JohnMcLear** [comment]
tnx for reporting btw¬ :D

**Comment by thegcat** [comment]
Been there done that. Doesn't get much better when they're older, there's just less poop to clean :-D Thanks!
