### ISSUE TITLE
MySQL improvements

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ueberDB#125]
As per https://github.com/ether/ueberDB/commit/7762f0096458bcb1ada3ad634d1a43f99a1354f0#r38822125:

I 've sent this to our DBA team. Per them, the fix is a hack, but seems fine to them. At least from their point of view, it does solve the issue.

As far as binary vs utf8mb4 goes, and strictly speaking, binary is more loose (and thus a superset of) than utf8mb4. That is, any sequence of bytes is valid for binary whereas not any sequence of bytes is valid for utf8mb4 (there are sequences of bytes that are not valid utf8 characters). However, in the context of this SELECT statement, since the first part of the WHERE clause already matches a utf8mb4 string of characters, the binary cast after that is going to be fine as the range of allowed bytes sequences has already been set.

As a note, and to make sure our installation would not be affected but this change, we also run a set of SELECT DISTINCT queries on our data to make sure we have no pads that would be problematic after this. We have seen no issue. We seem to have 141M+ distinct keys in our table, not sure how much that number helps you.

Being a bit pedantic, and ignoring the first part of the WHERE clause, inserting/replacing into a table/column that uses a charset+collation and then casting to binary when selecting is not great. But if you feel that you can maintain this, no objection on our side.

Being even more pedantic, the more correct move would be to move the keys column to varbinary, with the unfortunate caveat that invalid UTF8 characters in pad names would be possible. In that case the code would not need this hack. That being said, we are not familiar enough with the code nor the installed codebase to know how feasible such a conversion is, so we won't make any recommendation.

Thanks for trying to address this hairy issue.

**Edit** by @muxator: added the hyperlink to the original discussion by @akosiaris

**Comment by thegcat** [comment]
Regarding the comment that 

```sql
WHERE `key` = ? AND BINARY `key` = ?`
```

is a hack: as per https://dev.mysql.com/doc/refman/5.6/en/char.html "`PAD SPACE`", `=` on that column will ignore trailing whitespace, so you need any kind of second condition to guarantee the same number of trailing whitespaces too, thus the additional `BINARY` comparison. I'm not quite sure I'd call this a hack, rather a solution to the `PAD SPACE` behaviour.

Note though that this could be replaced with a

```sql
WHERE `key` LIKE ?
```

which would not be subject to the `PAD SPACE` problem. Furthermore as the `key` column collation is binary it would be case-sensitive. As long as you're throwing in a string without `%` or `_` (special characters for `LIKE`) you get the same result as above with index usage and more or less the same performance. This would require escaping `%` and `_` though so I'm not quite sure it's worth it.
