### ISSUE TITLE
Bulk delete on MySQL might still be slow because of BINARY comparison

### ISSUE THREAD

**Issue by thegcat** [ether/ueberDB#127]
The index-using non-`BINARY` short-circuit added to the single delete has not been added to the bulk delete.

https://github.com/ether/ueberDB/blob/master/mysql_db.js#L209 would need to be reworked to do the equivalent of:

```sql
WHERE `key` IN (?) AND BINARY `key` IN (?)
```

to get the index-speed of the first `IN` with the correctness with regard to trailing white spaces of the second `IN`.

**Comment by JohnMcLear** [comment]
You fucking MySQL my friend.

**Comment by muxator** [comment]
> The index-using non-BINARY short-circuit added to the single delete has not been added to the bulk delete.

Agreed. I'll post a PR.

**Comment by muxator** [comment]
@JohnMcLear, can you please test #129?
If it works (@thegcat: another pair of eyes may be of help), please include that in ueberDB and release a new version on npm.

My intention is doing a point release of Etherpad including the bare minimum changes needed for the performance regression on mysql & the CSS glitches fixed after 1.8.3.

**Comment by muxator** [comment]
My eyes are crossing. Closed by mistake, reopened now.

**Comment by JohnMcLear** [comment]
Gimme 30 mins.
