### ISSUE TITLE
MySQL performance: Replace REPLACE with INSERT ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by webzwo0i** [ether/ueberDB#151]
For inserting values into the database we use the `REPLACE` statement. `REPLACE` does an `INSERT` or, if it can't because a primary key is already in the table, does `DELETE` followed by an `INSERT`.

When using a normal pad, for every revision, the globalAuthor is updated to include the recent timestamp of her latest revision. That means for every revision, the `INSERT` of the globalAuthor will fail, and a `DELETE` followed by an `INSERT` is done.

This should be changed to instead use a `INSERT` with an `ON DUPLICATE KEY UPDATE`. That would circumvent the `DELETE`, resulting in only 2 instead of 3 operations on the database for every changeset.

**Comment by JohnMcLear** [comment]
```
This information is available via the InnoDB stats "Show Engine INNODB STATUS\G;"

--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
0 read views open inside InnoDB
Process ID=9905, Main thread ID=140364363052800, state: sleeping
Number of rows inserted 429805, updated 1429243, deleted 0, read 1595887
29.72 inserts/s, 91.45 updates/s, 0.00 deletes/s, 102.72 reads/s
Number of system rows inserted 0, updated 0, deleted 0, read 0
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 0.00 reads/s

The inserts/s, updates/s, deletes/s, and 111.40 reads/s stats are calculated in real time. The inserted, updated, deleted, and read stats are cumulated since MySQL started.
```

stats from a real world instance.

**Comment by webzwo0i** [comment]
Thanks for sharing. A look on https://dev.mysql.com/doc/refman/8.0/en/replace.html says:
```
It is possible that in the case of a duplicate-key error, a storage engine may perform the REPLACE as an update rather than a delete plus insert, but the semantics are the same.
```

Closing this, as at least InnoDB already uses UPDATE
