### ISSUE TITLE
In Mongodb dbName should not be mandatory

### ISSUE THREAD

**Issue by Loki-Afro** [ether/ueberDB#185]
..., because the database name can be part of the url itself.

https://github.com/ether/ueberDB/blob/8ed220f48a049ff81863c5ed4c61ccc4b28dee61/databases/mongodb_db.js#L20-L24

```
mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
```
 https://docs.mongodb.com/manual/reference/connection-string/
https://docs.mongodb.com/v4.4/reference/connection-string/#records-database

**Comment by rhansen** [comment]
cc @Sylchauf
