### ISSUE TITLE
mongodb : breaking change in new implementation key VS _id

### ISSUE THREAD

**Issue by brunob** [ether/ueberDB#201]
Hi, as discussed in #192 we are moving our etherpad instances from mongo 3 to 4 (we also switched from a local mongo db to a cluster mode). So we have dumped our mongo dbs from mongodb 3.2.11 with `mongodump` and imported these to our new mongo server running mongo 4.4.4 with `mongorestore`.

We realized that our new etherpad instances (running mongo 4.x) can't find our "old" pads that was available on mongo 3.x, eg `newpads.net/p/randomname` show a blank/new pad instead of the content available on `oldpads.net/p/randomname`.

After a bit of struggling, i found a big difference in the db, here is the entry of a pad created with the old implementation of mongodb in ueberDB :

``` json
{
    "_id" : ObjectId("60585c07f1b96ee7695bd494"),
    "key" : "pad:randomname",
    "val" : "{\"atext\":{\"text\":\"*...}"
}
```

And here is the same type of entry for a pad created on mongo 4.x with the latest mongodb implementation :

```json
{
        "_id" : "pad:randomname",
        "value" : "{\"atext\":{\"text\":\"*...}"
}
```

The diff comes from different implementation in `database.prototype.set` in mongo script ref :

https://github.com/ether/ueberDB/blob/bedbcb863504faafe9792a27d0bbd3ea1733ce99/databases/mongodb_db.js#L142
VS
https://github.com/ether/ueberDB/blob/master/databases/mongodb_db.js#L91

So, `this.collection.update({key}, {key, val: value}, {safe: true, upsert: true}, callback);` VS `this.collection.update({_id: key}, {$set: {value}}, {upsert: true}, callback);` shows that the mapping is completely different, leading to a breaking change.

Do you know if this change due to a mongodb change or only to ueberDB ? What is the preferred way for etherpad users to upgrade from mongo 3.x to 4.x ?

**Comment by brunob** [comment]
@rhansen nice plan to have a _legacy fork, but it will demand more maintenance effort for maintainers. Since mongo support was "officially" promoted in readme since less than 2 months https://github.com/ether/ueberDB/commit/3427db383abfc7e7a300e944806764b92b0e6073#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 maybe the change can come directly in mongo file without forking. There should be more existing users of legacy implementation than new users of the actual one (think to all etherpad's users running on mongo).

**Comment by rhansen** [comment]
If backwards compatibility didn't matter, which scheme would you say is better? I don't know much about mongodb, but I would guess that storing the key in `_id` is more efficient. If so, I think I would prefer a `_legacy` fork. I'm not too worried about maintenance hassle—we can make one subclass the other to maximize code reuse.

I would would be nice to get input from @Sylchauf before making any changes.

**Comment by brunob** [comment]
> but I would guess that storing the key in _id is more efficient

It could, since :

- _id is the primary key on documents in a collection; with it, documents (records) can be differentiated from each one another.
- _id is automatically indexed. Lookups specifying { _id: <someval> } refer to the _id index as their guide.
- By default the _id field is of type ObjectID, one of MongoDB's BSON types. Users can also override _id to something other than an ObjectID, if desired.

ref https://www.navicat.com/en/company/aboutus/blog/1010-all-about-mongodb-s-_id-field

Other side is that automatic generated ID seems to be useful for certain case :

> Since each ObjectId contains a timestamp, you can sort your documents by _id to by create time.

See also https://docs.mongodb.com/manual/core/document/#the-_id-field

**Comment by Sylchauf** [comment]
_id is usually the best idea/practice to store an ID in MongoDB Database. @brunob gives the rights reasons.
It's the most common pattern.

Maybe an alternative thing will be a { legacy: true } in the settings to avoid a file fork ?

Another option (with seems better and more future-proof) will be to create a migration guide for «old» databases

**Comment by rhansen** [comment]
> _id is usually the best idea/practice to store an ID in MongoDB Database. @brunob gives the rights reasons.
> It's the most common pattern.

OK, sounds like the current behavior is preferred (if we ignore compatibility). Thanks for the input.

> Maybe an alternative thing will be a { legacy: true } in the settings to avoid a file fork ?

Yes, that would work. I had originally decided against that approach because I thought it would make it more difficult to create a migration script, but I don't think that's the case.

@brunob What do you think about leaving the current behavior as the default and adding a `legacy: true` option?

> Another option (with seems better and more future-proof) will be to create a migration guide for «old» databases

It would be nice to have a generic migration script that would take a config for a source database and a config for a destination database and copy all records over. Such a script would not scale to large databases unless we overhaul ueberdb's internal API.

**Comment by brunob** [comment]
I think the migration guide/script is enough, if user can migrate their dbs to new layout legacy option would not really needed.

@Sylchauf do you have infos or clues about this migration as i can test it on our dbs and tell you if etherpad works well after that ?

**Comment by brunob** [comment]
@Sylchauf any news about this ?

**Comment by brunob** [comment]
Finally i think we are going to dump all our pads with a shell script using etherpad API and import them in the new instances with a similar script :\

**Comment by AlexanderS** [comment]
I used something like this to convert the legacy db format to the current format:

```
db.store.find().forEach(function(old){ db.ueberdb.insert({'_id': old.key, 'value': old.val}); });
```

**Comment by brunob** [comment]
I think this should be closed for stale.
