### ISSUE TITLE
Please document caching / shutdown behavior

### ISSUE THREAD

**Issue by kentonv** [ether/ueberDB#74]
Currently, if you write a script which makes a batch of calls to `db.set()`, followed by a call to `db.close()`, followed by `process.exit(0)`, properly waiting for all callbacks and checking errors, the process will exit successfully with nothing having actually been written. (Note: In my case I was using sqlite.)

It appears that:
- By default, all writes are cached in memory and only written back periodically.
- Callbacks report success before data has actually been written.
- `db.close()` immediately closes the underlying database _without_ flushing the cache first, and reports no error if the cache is non-empty.
- If you don't exit right away, the cache flush will still happen some time later and the underlying database will report errors because it is already closed.
- You are supposed to call `db.doShutdown(callback)` in order to actually wait for a cache flush, but this method is not documented in the readme or anywhere else. In fact, the example in the readme looks like it should be using this method, but isn't, and therefore won't actually store anything to the database.

I would argue that:
- `doShutdown()` should be prominently documented and used in the example.
- Alternatively, `close()` should implicitly call `doShutdown()`, which is the behavior I had expected. (An `abort()` method could be provided as a way to close without flushing the cache, if desired.)
- When `set()` or other write methods take a callback, the callback should not be called until the data has actually been synced to disk. If the caller doesn't care about this, they don't need to provide a callback. If they provide a callback, they presumably did so because they want to know when the data is safely saved.

**Comment by muxator** [comment]
Agreed, this should be documented.
